// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg9PWzs36YvsJTnQAsNNgSSsR1SrS_i-U',
    appId: '1:662324845842:web:61d5baa17e8ce201c627cb',
    messagingSenderId: '662324845842',
    projectId: 'expense-31597',
    authDomain: 'expense-31597.firebaseapp.com',
    databaseURL: 'https://expense-31597-default-rtdb.firebaseio.com',
    storageBucket: 'expense-31597.firebasestorage.app',
    measurementId: 'G-D05GTNWDP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM7hSwzlRnTO_ouxR2IFcdFr-j3w9Ohpo',
    appId: '1:662324845842:android:2cb2dabffdc86743c627cb',
    messagingSenderId: '662324845842',
    projectId: 'expense-31597',
    databaseURL: 'https://expense-31597-default-rtdb.firebaseio.com',
    storageBucket: 'expense-31597.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAro_jw5QJP9FaIw7BAe-BfOJUwpAeaGJI',
    appId: '1:662324845842:ios:6ece019e0264178ec627cb',
    messagingSenderId: '662324845842',
    projectId: 'expense-31597',
    databaseURL: 'https://expense-31597-default-rtdb.firebaseio.com',
    storageBucket: 'expense-31597.firebasestorage.app',
    iosBundleId: 'com.example.crudeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAro_jw5QJP9FaIw7BAe-BfOJUwpAeaGJI',
    appId: '1:662324845842:ios:6ece019e0264178ec627cb',
    messagingSenderId: '662324845842',
    projectId: 'expense-31597',
    databaseURL: 'https://expense-31597-default-rtdb.firebaseio.com',
    storageBucket: 'expense-31597.firebasestorage.app',
    iosBundleId: 'com.example.crudeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg9PWzs36YvsJTnQAsNNgSSsR1SrS_i-U',
    appId: '1:662324845842:web:650d797768dd593dc627cb',
    messagingSenderId: '662324845842',
    projectId: 'expense-31597',
    authDomain: 'expense-31597.firebaseapp.com',
    databaseURL: 'https://expense-31597-default-rtdb.firebaseio.com',
    storageBucket: 'expense-31597.firebasestorage.app',
    measurementId: 'G-Q6VRY09BD3',
  );
}
