// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZUH_CbZogQADyDUHIwId5IFaH-DbMvZs',
    appId: '1:164281630162:web:d821b5e03f0155d5095c0b',
    messagingSenderId: '164281630162',
    projectId: 'day-two-firebase',
    authDomain: 'day-two-firebase.firebaseapp.com',
    storageBucket: 'day-two-firebase.firebasestorage.app',
    measurementId: 'G-L2TCB7PN7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7mVO1CdP_E1fdV15zyipfYgxKjEh9GGs',
    appId: '1:164281630162:android:f58a0ad5a767703d095c0b',
    messagingSenderId: '164281630162',
    projectId: 'day-two-firebase',
    storageBucket: 'day-two-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdZT4-KGrV9WrQ4JT2-nyfMNkxvQJkVbg',
    appId: '1:164281630162:ios:83f73ea380ce0c74095c0b',
    messagingSenderId: '164281630162',
    projectId: 'day-two-firebase',
    storageBucket: 'day-two-firebase.firebasestorage.app',
    iosBundleId: 'com.example.dayTwoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdZT4-KGrV9WrQ4JT2-nyfMNkxvQJkVbg',
    appId: '1:164281630162:ios:83f73ea380ce0c74095c0b',
    messagingSenderId: '164281630162',
    projectId: 'day-two-firebase',
    storageBucket: 'day-two-firebase.firebasestorage.app',
    iosBundleId: 'com.example.dayTwoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZUH_CbZogQADyDUHIwId5IFaH-DbMvZs',
    appId: '1:164281630162:web:a4b48b0c35afbe6e095c0b',
    messagingSenderId: '164281630162',
    projectId: 'day-two-firebase',
    authDomain: 'day-two-firebase.firebaseapp.com',
    storageBucket: 'day-two-firebase.firebasestorage.app',
    measurementId: 'G-Y7F2V1254D',
  );
}
